require(shiny)


shinyUI(
  fluidPage(
    br(),
    titlePanel(h2("Stock/Index Price Dashboard",align = 'center')),
    br(),
    fluidRow(
      column(3, 
             wellPanel(
               radioButtons(inputId = 'stock_plot_type',
                            label = 'Select plot type:',
                            choices = c('Candlestick plot' = 'candle',
                                        'Closing data only' = 'closing'),
                            selected = 'candle',
                            inline = TRUE),
               selectInput(inputId = 'stock_ticker',
                           label = 'Select a company for stock price information:',
                           choices = list('Consumer/Medical Goods' = list('Apple' = 'AAPL',
                                                                          'Becton, Dickinson and Company (BD)' = 'BDX',
                                                                          'Church & Dwight' = 'CHD',
                                                                          'Colgate-Palmolive' = 'CL',
                                                                          'Proctor & Gamble' = 'PG',
                                                                          'Tesla' = 'TSLA',
                                                                          'Unilever' = 'UL'),
                                          'Chemical & Functional Materials' = list('Air Liquide (Euronext Paris)' = 'AI.PA',
                                                                                   'Air Products' = 'APD',
                                                                                   'BASF SE (Frankfurt Stock Exchange)' = 'BAS.DE',
                                                                                   'Dow' = 'DOW',
                                                                                   'DuPont' = 'DD',
                                                                                   'Eastman Chemical Company' = 'EMN',
                                                                                   'Ecolab' = 'ECL',
                                                                                   'Evonik Industries AG (Frankfurt Stock Exchange)' = 'EVK.DE',
                                                                                   'Huntsman Corporation' = 'HUN',
                                                                                   'Johnson Matthey (London Stock Exchange)' = 'JMAT.L',
                                                                                   'Linde (Frankfurt Stock Exchange)' = 'LIN.DE',
                                                                                   'Linde (NY Stock Exchange)' = 'LIN',
                                                                                   'LyondellBasell' = 'LYB',
                                                                                   '3M' = 'MMM',
                                                                                   'Sumitomo Chemical (Tokyo Stock Exchange)' = '4005.T',
                                                                                   'Tosoh (Tokyo Stock Exchange)' = '4042.T'),
                                          'Cosmetics' = list("L'Oreal S.A. (Euronext Paris)" = 'OR.PA',
                                                             'Shiseido (Tokyo Stock Exchange)' = '4911.T'),
                                          'Food & Fragrances' = list('IFF' = 'IFF',
                                                                     'Kellogg Company' = 'K',
                                                                     'The Kraft Heinz Company' = 'KHC',
                                                                     'Mondelez International' = 'MDLZ',
                                                                     'Nestle S.A. (SIX Swiss Exchange)' = 'NESN.SW'),
                                          'Oil, Gas, & Energy' = list('BP (NY Stock Exchange)' = 'BP',
                                                                      'BP (London Stock Exchange)' = 'BP.L',
                                                                      'Chevron' = 'CVX',
                                                                      # 'China Petroleum & Chemical (Sinopec) (NY Stock Exchange)' = 'SNP',
                                                                      'China Petroleum & Chemical (Sinopec) (Hong Kong Stock Exchange)' = '0386.HK',
                                                                      'China Petroleum & Chemical (Sinopec) (Shanghai Stock Exchange)' = '600028.SS',
                                                                      'ConocoPhillips' = 'COP',
                                                                      'ExxonMobil' = 'XOM',
                                                                      'Marathon Petroleum' = 'MPC',
                                                                      # 'PetroChina (NY Stock Exchange)' = 'PTC',
                                                                      'PetroChina (Hong Kong Stock Exchange)' = '0857.HK',
                                                                      'PetroChina (Shanghai Stock Exchange)' = '601857.SS',
                                                                      'Shell (NY Stock Exchange)' = 'SHEL',
                                                                      'Shell (London Stock Exchange)' = 'SHEL.L'),
                                          'Pharmaceuticals' = list('Amgen' = 'AMGN',
                                                                   'Bayer AG (Frankfurt Stock Exchange)' = 'BAYN.DE',
                                                                   'Bristol Myers Squibb' = 'BMY',
                                                                   'Johnson & Johnson' = 'JNJ',
                                                                   'Merck' = 'MRK',
                                                                   'Pfizer' = 'PFE',
                                                                   'Roche (SIX Swiss Exchange)' = 'ROG.SW'),
                                          'Retailers' = list('Amazon' = 'AMZN',
                                                             'Target' = 'TGT',
                                                             'Walmart' = 'WMT')),
                           selected = 'AAPL'),
               tags$style(type='text/css', ".selectize-dropdown-content {max-height: 300px; }"),
               radioButtons(inputId = 'stock_plot_date_select',
                            label = 'Specify date entry type:',
                            choices = c('Date range' = 'stock_date_range',
                                        'Days back from now' = 'stock_days_back'),
                            selected = 'stock_date_range',
                            inline = TRUE),
               conditionalPanel(condition = "input.stock_plot_date_select == 'stock_days_back'",
                                numericInput(inputId = 'stock_tail_days',
                                             label = '# of days to display back from today (min 2):',
                                             30,
                                             min = 2)),
               conditionalPanel(condition = "input.stock_plot_date_select == 'stock_date_range'",
                                dateRangeInput(inputId = 'stock_date_range',
                                               label = 'Date range to display:',
                                               start = Sys.Date() - 30,
                                               end = Sys.Date(),
                                               max = Sys.Date())),
               conditionalPanel(condition = "input.stock_plot_date_select == 'stock_date_range'",
                                actionButton(inputId = 'stock_date_reset_button',
                                             label = 'Reset to default dates')),
               conditionalPanel(condition = "input.stock_plot_type == 'candle'",
                                checkboxInput(inputId = 'moving_average_check',
                                              label = 'Display closing price moving average?',
                                              value = FALSE)),
               conditionalPanel(condition = "input.moving_average_check == 1",
                                numericInput(inputId = 'moving_average_days',
                                             label = '# of days to use for moving average (min 2):',
                                             7,
                                             min = 2))
               )
             ),
      column(6, plotOutput("stock_plot")),
      column(3,
             wellPanel(
               h4(textOutput('stock_summary_table_title')),
               tableOutput('stock_summary_table')) 
             )
    ),
    br(),
    fluidRow(
      column(3,
             wellPanel(
               radioButtons(inputId = 'index_plot_type',
                            label = 'Select plot type:',
                            choices = c('Candlestick plot' = 'candle',
                                        'Closing data only' = 'closing'),
                            selected = 'candle',
                            inline = TRUE),
               selectInput(inputId = 'selected_index',
                            label= 'Select an index to plot:',
                            choices = list('North America' = list('S&P500 (NY Stock Exchange)' = '^GSPC',
                                                                  'Dow Jones (NY Stock Exchange)' = '^DJI',
                                                                  'NASDAQ (NY Stock Exchange)' = '^IXIC',
                                                                  'NYSE Composite (NY Stock Exchange)' = '^NYA'),
                                           'Europe' = list('Dax Performance Index (Frankfurt Stock Exchange)' = '^GDAXI',
                                                           'FTSE 100 (London Stock Exchange)' = '^FTSE'),
                                           'Asia' = list('Hang Seng Index (Hong Kong Stock Exchange)' = '^HSI',
                                                         'Shanghai SE Composite Index (Shanghai Stock Exchange)' = '000001.SS',
                                                         'CSI 300 (Shanghai Stock Exchange)' = '000300.SS',
                                                         'Nikkei 225 (Tokyo Stock Exchange)' = '^N225')
                                           ),
                            selected = 'S&P500'),
               radioButtons(inputId = 'index_plot_date_select',
                            label = 'Specify date entry type:',
                            choices = c('Date range' = 'index_date_range',
                                        'Days back from now' = 'index_days_back'),
                            selected = 'index_date_range',
                            inline = TRUE),
               conditionalPanel(condition = "input.index_plot_date_select == 'index_days_back'",
                                numericInput(inputId = 'index_tail_days',
                                             label = '# of days to display back from today (min 2):',
                                             30,
                                             min = 2)),
               conditionalPanel(condition = "input.index_plot_date_select == 'index_date_range'",
                                dateRangeInput(inputId = 'index_date_range',
                                               label = 'Date range to display:',
                                               start = Sys.Date() - 30,
                                               end = Sys.Date())),
               conditionalPanel(condition = "input.index_plot_date_select == 'index_date_range'",
                                actionButton(inputId = 'index_date_reset_button',
                                             label = 'Reset to default dates'))
             )),
      column(6, plotOutput('index_plot')),
      column(3,
             wellPanel(
               h4(textOutput('index_summary_table_title')),
               tableOutput('index_summary_table'))
             )
    )
  )
)
